services:
  - type: web
    name: fitness-app-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fitness-app-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
      - key: NODE_ENV
        value: production

databases:
  - name: fitness-app-db
    plan: free
    databaseName: fitness_db
    user: fitness_user
